import * as stylex from "@stylexjs/stylex";
import { tokens } from "./tokens.stylex";
export const s = stylex.create({
  html: {
    colorScheme: "dark",
    backgroundColor: tokens.paper,
    scrollBehavior: {
      default: "smooth",
      "@media (prefers-reduced-motion: reduce)": "auto",
    },
    scrollPaddingTop: 24,
  },
  body: {
    margin: 0,
    backgroundColor: tokens.paper,
    color: tokens.ink,
    fontFamily: tokens.font,
    fontSize: 16,
    lineHeight: 1.6,
    letterSpacing: "normal",
    WebkitFontSmoothing: "antialiased",
  },
  main: { paddingInline: tokens.gutter },
  link: {
    transition: {
      default: "color 140ms ease-out",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    color: { default: "inherit", ":hover": tokens.accent },
    textDecoration: "none",
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accent}`,
    },
    outlineOffset: 4,
  },
  skip: {
    position: "absolute",
    top: { default: -100, ":focus": 12 },
    left: 16,
    padding: 12,
    zIndex: 10,
    backgroundColor: tokens.paper,
  },
  header: {
    marginInline: tokens.gutter,
    paddingBlock: 32,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 24,
    flexWrap: "wrap",
    borderBottom: `1px solid ${tokens.line}`,
  },
  brand: {
    fontSize: 20,
    lineHeight: "28px",
    fontWeight: 500,
    color: { default: tokens.ink, ":hover": tokens.ink },
    transition: "none",
  },
  brandText: { whiteSpace: "pre" },
  brandLetter: (delay: number) => ({
    color: tokens.ink,
    transitionProperty: "color",
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "cubic-bezier(0.2, 0.7, 0.3, 1)",
    transitionDelay: {
      default: `${delay}ms`,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  }),
  brandLetterActive: { color: tokens.accent },
  brandOrnament: {
    color: tokens.accent,
    display: "inline-block",
    fontSize: 26,
    lineHeight: 0,
    verticalAlign: "-2px",
  },
  footer: {
    marginInline: tokens.gutter,
    marginTop: 48,
    paddingBlock: 32,
    borderTop: `1px solid ${tokens.line}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: 32,
    flexWrap: "wrap",
  },
  footerCopy: { margin: 0, maxWidth: 520, color: tokens.muted },
  footerLinks: { display: "flex", flexWrap: "wrap", gap: 24 },
  heading: {
    margin: 0,
    fontSize: 20,
    lineHeight: "28px",
    fontWeight: 500,
    letterSpacing: "normal",
  },
  subheading: {
    margin: 0,
    fontSize: 16,
    lineHeight: "26px",
    fontWeight: 400,
    letterSpacing: "normal",
  },
  muted: { color: tokens.muted },
  paragraph: { margin: 0, fontSize: 16, lineHeight: "26px" },
  toolbar: {
    paddingBlock: 32,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
    gap: 24,
    flexWrap: "wrap",
  },
  toolbarCopy: { display: "flex", flexDirection: "column", gap: 8 },
  toolbarActions: {
    display: "flex",
    gap: 24,
    alignItems: "center",
    color: tokens.muted,
  },
  button: {
    fontFamily: "inherit",
    fontSize: 16,
    lineHeight: "26px",
    fontWeight: 400,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    textAlign: "left",
    color: { default: "inherit", ":hover": tokens.accent },
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.3 },
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accent}`,
    },
    outlineOffset: 4,
  },
  gallery: {
    // Virtual spacers preserve position; native anchoring must not move it again.
    overflowAnchor: "none",
  },
  row: {
    display: { default: "flex", "@media (max-width: 900px)": "block" },
    gap: 8,
    marginBottom: { default: 8, "@media (max-width: 900px)": 0 },
    alignItems: "start",
  },
  figure: (ratio: number) => ({
    margin: 0,
    marginBottom: { default: 0, "@media (max-width: 900px)": 8 },
    minWidth: 0,
    flexBasis: 0,
    flexGrow: ratio,
  }),
  photoLink: {
    display: "block",
    width: "100%",
    cursor: "pointer",
    borderRadius: 2,
  },
  photo: { display: "block", width: "100%", height: "auto", borderRadius: 2 },
  entry: {
    paddingBlock: 32,
    display: { default: "flex", "@media (min-width: 901px)": "contents" },
    flexDirection: "column",
    gap: 32,
  },
  spacer: (height: number) => ({ height, pointerEvents: "none" }),
  entryImage: {
    display: "block",
    width: "100%",
    height: "auto",
    marginInline: "auto",
    borderRadius: 2,
  },
  detailFrame: {
    display: { default: "block", "@media (min-width: 901px)": "grid" },
    gridTemplateColumns: "320px minmax(0, 1fr)",
    gridTemplateRows: "auto 1fr auto",
    minHeight: "100dvh",
  },
  detailBrand: {
    position: { default: "static", "@media (min-width: 901px)": "fixed" },
    top: 0,
    left: 0,
    width: { default: "auto", "@media (min-width: 901px)": 320 },
    zIndex: 1,
    backgroundColor: tokens.paper,
    gridColumn: 1,
    gridRow: 1,
    marginInline: 0,
    paddingInline: tokens.gutter,
    borderBottomWidth: 0,
  },
  detailMain: {
    display: { default: "block", "@media (min-width: 901px)": "contents" },
  },
  detailMetadata: {
    position: { default: "static", "@media (min-width: 901px)": "fixed" },
    // The brand occupies 28px of line height plus 32px padding on each side.
    top: 92,
    left: 0,
    width: { default: "auto", "@media (min-width: 901px)": 320 },
    maxHeight: { default: "none", "@media (min-width: 901px)": "calc(100dvh - 92px)" },
    overflowY: { default: "visible", "@media (min-width: 901px)": "auto" },
    zIndex: 1,
    backgroundColor: tokens.paper,
    gridColumn: 1,
    gridRow: 2,
    minWidth: 0,
    padding: { default: 0, "@media (min-width: 901px)": "32px" },
  },
  expandablePhoto: {
    gridColumn: 2,
    gridRow: "1 / 4",
    minWidth: 0,
    backgroundColor: "#161616",
    padding: { default: "16px", "@media (min-width: 901px)": "32px" },
    marginInline: { default: "-16px", "@media (min-width: 901px)": 0 },
    overflowAnchor: "none",
  },
  photoToggle: {
    display: "block",
    width: "100%",
    marginInline: "auto",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "zoom-in",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.accent}` },
    outlineOffset: 4,
  },
  photoToggleFitted: (ratio: number) => ({
    width: {
      default: `min(100%, ${ratio * 78}dvh)`,
      "@media (min-width: 901px)": `min(100%, calc((100dvh - 64px) * ${ratio}))`,
    },
  }),
  photoToggleExpanded: { cursor: "zoom-out" },
  entryHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    fontSize: 16,
    lineHeight: 1.6,
  },
  entryBack: { display: "flex", flexDirection: "column", gap: 24 },
  entryBackLink: { color: { default: tokens.muted, ":hover": tokens.accent } },
  entryHeading: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    columnGap: 16,
    rowGap: 0,
    margin: 0,
    fontSize: "inherit",
    fontWeight: 400,
    lineHeight: "inherit",
  },
  entryMetadata: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    columnGap: 16,
    rowGap: 0,
    color: tokens.muted,
  },
  entryNote: { margin: 0, whiteSpace: "pre-wrap" },
  keyboardHint: {
    margin: 0,
    color: tokens.muted,
    fontSize: 14,
    lineHeight: "22px",
    textAlign: "center",
  },
  pagination: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    paddingBlock: 32,
  },
  notFound: {
    paddingBlock: 80,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
});
