import * as stylex from "@stylexjs/stylex";
import { tokens } from "./tokens.stylex";
export const s = stylex.create({
  html: {
    colorScheme: "dark",
    backgroundColor: tokens.paper,
    scrollBehavior: {
      default: "smooth",
      "@media (prefers-reduced-motion: reduce)": "auto",
    },
    scrollPaddingTop: 24,
  },
  body: {
    margin: 0,
    backgroundColor: tokens.paper,
    color: tokens.ink,
    fontFamily: tokens.font,
    fontSize: 16,
    lineHeight: 1.6,
    letterSpacing: "normal",
    WebkitFontSmoothing: "antialiased",
  },
  main: { paddingInline: tokens.gutter },
  link: {
    transition: {
      default: "color 140ms ease-out",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    color: { default: "inherit", ":hover": tokens.accent },
    textDecoration: "none",
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accent}`,
    },
    outlineOffset: 4,
  },
  skip: {
    position: "absolute",
    top: { default: -100, ":focus": 12 },
    left: 16,
    padding: 12,
    zIndex: 10,
    backgroundColor: tokens.paper,
  },
  header: {
    marginInline: tokens.gutter,
    paddingBlock: 32,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 24,
    flexWrap: "wrap",
    borderBottom: `1px solid ${tokens.line}`,
  },
  brand: {
    fontSize: 20,
    lineHeight: "28px",
    fontWeight: 500,
    color: { default: tokens.ink, ":hover": tokens.ink },
    transition: "none",
  },
  brandText: { whiteSpace: "pre" },
  brandLetter: (delay: number) => ({
    color: tokens.ink,
    transitionProperty: "color",
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "cubic-bezier(0.2, 0.7, 0.3, 1)",
    transitionDelay: {
      default: `${delay}ms`,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  }),
  brandLetterActive: { color: tokens.accent },
  brandOrnament: {
    color: tokens.accent,
    display: "inline-block",
    fontSize: 26,
    lineHeight: 0,
    verticalAlign: "-2px",
  },
  footer: {
    marginInline: tokens.gutter,
    marginTop: 48,
    paddingBlock: 32,
    borderTop: `1px solid ${tokens.line}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: 32,
    flexWrap: "wrap",
  },
  footerCopy: { margin: 0, maxWidth: 520, color: tokens.muted },
  footerLinks: { display: "flex", flexWrap: "wrap", gap: 24 },
  heading: {
    margin: 0,
    fontSize: 20,
    lineHeight: "28px",
    fontWeight: 500,
    letterSpacing: "normal",
  },
  subheading: {
    margin: 0,
    fontSize: 16,
    lineHeight: "26px",
    fontWeight: 400,
    letterSpacing: "normal",
  },
  muted: { color: tokens.muted },
  paragraph: { margin: 0, fontSize: 16, lineHeight: "26px" },
  toolbar: {
    paddingBlock: 32,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
    gap: 24,
    flexWrap: "wrap",
  },
  toolbarCopy: { display: "flex", flexDirection: "column", gap: 8 },
  toolbarActions: {
    display: "flex",
    gap: 24,
    alignItems: "center",
    color: tokens.muted,
  },
  button: {
    fontFamily: "inherit",
    fontSize: 16,
    lineHeight: "26px",
    fontWeight: 400,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    textAlign: "left",
    color: { default: "inherit", ":hover": tokens.accent },
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.3 },
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accent}`,
    },
    outlineOffset: 4,
  },
  row: {
    display: { default: "flex", "@media (max-width: 600px)": "block" },
    gap: 8,
    marginBottom: { default: 8, "@media (max-width: 600px)": 0 },
    alignItems: "start",
  },
  figure: (ratio: number) => ({
    margin: 0,
    marginBottom: { default: 0, "@media (max-width: 600px)": 8 },
    minWidth: 0,
    flexBasis: 0,
    flexGrow: ratio,
  }),
  photoLink: {
    display: "block",
    width: "100%",
    cursor: "pointer",
    borderRadius: 2,
  },
  photo: { display: "block", width: "100%", height: "auto", borderRadius: 2 },
  entry: {
    paddingBlock: 32,
    display: "flex",
    flexDirection: "column",
    gap: 32,
  },
  spacer: (height: number) => ({ height, pointerEvents: "none" }),
  entryImage: (ratio: number) => ({
    display: "block",
    width: `min(100%, ${ratio * 78}dvh)`,
    height: "auto",
    marginInline: "auto",
    borderRadius: 2,
  }),
  entryHeader: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 24,
    rowGap: 8,
    fontSize: 16,
    lineHeight: 1.6,
  },
  entryBack: {
    display: "block",
    position: "relative",
  },
  entryBackHitArea: {
    position: "absolute",
    insetBlock: -20,
    insetInlineStart: -16,
    insetInlineEnd: 0,
  },
  entryBackArrow: {
    position: "absolute",
    insetInlineStart: 0,
    top: -8,
    height: 42,
    width: 24,
    display: "flex",
    alignItems: "center",
    color: tokens.muted,
    textDecoration: "none",
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accent}`,
    },
    outlineOffset: 2,
    opacity: {
      default: 0,
      "@media (max-width: 600px), (hover: none)": 1,
      [stylex.when.ancestor(":hover")]: 1,
      [stylex.when.ancestor(":focus-within")]: 1,
    },
    transition: {
      default: "opacity 180ms ease-out",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  entryBackContent: {
    width: "calc(100% - 24px)",
    transform: {
      default: "translateX(0)",
      "@media (max-width: 600px), (hover: none)": "translateX(24px)",
      [stylex.when.ancestor(":hover")]: "translateX(24px)",
      [stylex.when.ancestor(":focus-within")]: "translateX(24px)",
    },
    transition: {
      default: "transform 180ms cubic-bezier(0.2, 0.7, 0.3, 1)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  entryHeading: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: 16,
    rowGap: 8,
    margin: 0,
    fontSize: "inherit",
    fontWeight: 400,
    lineHeight: "inherit",
  },
  entryMetadata: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: 16,
    rowGap: 8,
    color: tokens.muted,
  },
  entryNote: { margin: 0, whiteSpace: "pre-wrap" },
  keyboardHint: {
    margin: 0,
    color: tokens.muted,
    fontSize: 14,
    lineHeight: "22px",
    textAlign: "center",
  },
  pagination: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    paddingBlock: 32,
  },
  notFound: {
    paddingBlock: 80,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
});
